"""created column stream

Revision ID: 73a1b9458d43
Revises: 
Create Date: 2020-08-18 16:57:28.032070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a1b9458d43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tech', sa.Column('stream', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tech', 'stream')
    # ### end Alembic commands ###
